#[allow(non_camel_case_types)]
#[derive(Debug, Clone)]
pub enum I {
    S_MOV_B32,
    S_MOV_B64,
    S_CMOV_B32,
    S_CMOV_B64,
    S_NOT_B32,
    S_NOT_B64,
    S_WQM_B32,
    S_WQM_B64,
    S_BREV_B32,
    S_BREV_B64,
    S_BCNT0_I32_B32,
    S_BCNT0_I32_B64,
    S_BCNT1_I32_B32,
    S_BCNT1_I32_B64,
    S_FF0_I32_B32,
    S_FF0_I32_B64,
    S_FF1_I32_B32,
    S_FF1_I32_B64,
    S_FLBIT_I32_B32,
    S_FLBIT_I32_B64,
    S_FLBIT_I32,
    S_FLBIT_I32_I64,
    S_SEXT_I32_I8,
    S_SEXT_I32_I16,
    S_BITSET0_B32,
    S_BITSET0_B64,
    S_BITSET1_B32,
    S_BITSET1_B64,
    S_GETPC_B64,
    S_SETPC_B64,
    S_SWAPPC_B64,
    S_RFE_B64,
    S_AND_SAVEEXEC_B64,
    S_OR_SAVEEXEC_B64,
    S_XOR_SAVEEXEC_B64,
    S_ANDN2_SAVEEXEC_B64,
    S_ORN2_SAVEEXEC_B64,
    S_NAND_SAVEEXEC_B64,
    S_NOR_SAVEEXEC_B64,
    S_XNOR_SAVEEXEC_B64,
    S_QUADMASK_B32,
    S_QUADMASK_B64,
    S_MOVRELS_B32,
    S_MOVRELS_B64,
    S_MOVRELD_B32,
    S_MOVRELD_B64,
    S_CBRANCH_JOIN,
    S_ABS_I32,
    S_SET_GPR_IDX_IDX,

    S_ADD_U32,
    S_SUB_U32,
    S_ADD_I32,
    S_SUB_I32,
    S_ADDC_U32,
    S_SUBB_U32,
    S_MIN_I32,
    S_MIN_U32,
    S_MAX_I32,
    S_MAX_U32,
    S_CSELECT_B32,
    S_CSELECT_B64,
    S_AND_B32,
    S_AND_B64,
    S_OR_B32,
    S_OR_B64,
    S_XOR_B32,
    S_XOR_B64,
    S_ANDN2_B32,
    S_ANDN2_B64,
    S_ORN2_B32,
    S_ORN2_B64,
    S_NAND_B32,
    S_NAND_B64,
    S_NOR_B32,
    S_NOR_B64,
    S_XNOR_B32,
    S_XNOR_B64,
    S_LSHL_B32,
    S_LSHL_B64,
    S_LSHR_B32,
    S_LSHR_B64,
    S_ASHR_I32,
    S_ASHR_I64,
    S_BFM_B32,
    S_BFM_B64,
    S_MUL_I32,
    S_BFE_U32,
    S_BFE_I32,
    S_BFE_U64,
    S_BFE_I64,
    S_CBRANCH_G_FORK,
    S_ABSDIFF_I32,
    S_RFE_RESTORE_B64,

    S_MOVK_I32,
    S_CMOVK_I32,
    S_CMPK_EQ_I32,
    S_CMPK_LG_I32,
    S_CMPK_GT_I32,
    S_CMPK_GE_I32,
    S_CMPK_LT_I32,
    S_CMPK_LE_I32,
    S_CMPK_EQ_U32,
    S_CMPK_LG_U32,
    S_CMPK_GT_U32,
    S_CMPK_GE_U32,
    S_CMPK_LT_U32,
    S_CMPK_LE_U32,
    S_ADDK_I32,
    S_MULK_I32,
    S_CBRANCH_I_FORK,
    S_GETREG_B32,
    S_SETREG_B32,
    S_SETREG_IMM32_B32,

    S_MOV_B32S_MOV_B32,

    S_CMP_EQ_I32,
    S_CMP_LG_I32,
    S_CMP_GT_I32,
    S_CMP_GE_I32,
    S_CMP_LT_I32,
    S_CMP_LE_I32,
    S_CMP_EQ_U32,
    S_CMP_LG_U32,
    S_CMP_GT_U32,
    S_CMP_GE_U32,
    S_CMP_LT_U32,
    S_CMP_LE_U32,
    S_BITCMP0_B32,
    S_BITCMP1_B32,
    S_BITCMP0_B64,
    S_BITCMP1_B64,
    S_SETVSKIP,
    S_SET_GPR_IDX_ON,
    S_CMP_EQ_U64,
    S_CMP_NE_U64,

    S_NOP,
    S_ENDPGM,
    S_BRANCH,
    S_CBRANCH_SCC0,
    S_CBRANCH_SCC1,
    S_CBRANCH_VCCZ,
    S_CBRANCH_VCCNZ,
    S_CBRANCH_EXECZ,
    S_CBRANCH_EXECNZ,
    S_BARRIER,
    S_SETKILL,
    S_WAITCNT,
    S_SETHALT,
    S_SLEEP,
    S_SETPRIO,
    S_SENDMSG,
    S_SENDMSGHALT,
    S_TRAP,
    S_ICACHE_INV,
    S_INCPERFLEVEL,
    S_DECPERFLEVEL,
    S_TTRACEDATA,
    S_CBRANCH_CDBGSYS,
    S_CBRANCH_CDBGUSER,
    S_CBRANCH_CDBGSYS_OR_USER,
    S_CBRANCH_CDBGSYS_AND_USER,
    S_ENDPGM_SAVED,
    S_SET_GPR_IDX_OFF,
    S_SET_GPR_IDX_MODE,

    V_CNDMASK_B32,
    V_ADD_F32,
    V_SUB_F32,
    V_SUBREV_F32,
    V_MUL_LEGACY_F32,
    V_MUL_F32,
    V_MUL_I32_I24,
    V_MUL_HI_I32_I24,
    V_MUL_U32_U24,
    V_MUL_HI_U32_U24,
    V_MIN_F32,
    V_MAX_F32,
    V_MIN_I32,
    V_MAX_I32,
    V_MIN_U32,
    V_MAX_U32,
    V_LSHRREV_B32,
    V_ASHRREV_I32,
    V_LSHLREV_B32,
    V_AND_B32,
    V_OR_B32,
    V_XOR_B32,
    V_MAC_F32,
    V_MADMK_F32,
    V_MADAK_F32,
    V_ADD_U32,
    V_SUB_U32,
    V_SUBREV_U32,
    V_ADDC_U32,
    V_SUBB_U32,
    V_SUBBREV_U32,
    V_ADD_F16,
    V_SUB_F16,
    V_SUBREV_F16,
    V_MUL_F16,
    V_MAC_F16,
    V_MADMK_F16,
    V_MADAK_F16,
    V_ADD_U16,
    V_SUB_U16,
    V_SUBREV_U16,
    V_MUL_LO_U16,
    V_LSHLREV_B16,
    V_LSHRREV_B16,
    V_ASHRREV_I16,
    V_MAX_F16,
    V_MIN_F16,
    V_MAX_U16,
    V_MAX_I16,
    V_MIN_U16,
    V_MIN_I16,
    V_LDEXP_F16,

    V_NOP,
    V_MOV_B32,
    V_READFIRSTLANE_B32,
    V_CVT_I32_F64,
    V_CVT_F64_I32,
    V_CVT_F32_I32,
    V_CVT_F32_U32,
    V_CVT_U32_F32,
    V_CVT_I32_F32,
    V_MOV_FED_B32,
    V_CVT_F16_F32,
    V_CVT_F32_F16,
    V_CVT_RPI_I32_F32,
    V_CVT_FLR_I32_F32,
    V_CVT_OFF_F32_I4,
    V_CVT_F32_F64,
    V_CVT_F64_F32,
    V_CVT_F32_UBYTE0,
    V_CVT_F32_UBYTE1,
    V_CVT_F32_UBYTE2,
    V_CVT_F32_UBYTE3,
    V_CVT_U32_F64,
    V_CVT_F64_U32,
    V_TRUNC_F64,
    V_CEIL_F64,
    V_RNDNE_F64,
    V_FLOOR_F64,
    V_FRACT_F32,
    V_TRUNC_F32,
    V_CEIL_F32,
    V_RNDNE_F32,
    V_FLOOR_F32,
    V_EXP_F32,
    V_LOG_CLAMP_F32,
    V_LOG_F32,
    V_RCP_CLAMP_F32,
    V_RCP_LEGACY_F32,
    V_RCP_F32,
    V_RCP_IFLAG_F32,
    V_RSQ_CLAMP_F32,
    V_RSQ_LEGACY_F32,
    V_RSQ_F32,
    V_RCP_F64,
    V_RCP_CLAMP_F64,
    V_RSQ_F64,
    V_RSQ_CLAMP_F64,
    V_SQRT_F32,
    V_SQRT_F64,
    V_SIN_F32,
    V_COS_F32,
    V_NOT_B32,
    V_BFREV_B32,
    V_FFBH_U32,
    V_FFBL_B32,
    V_FFBH_I32,
    V_FREXP_EXP_I32_F64,
    V_FREXP_MANT_F64,
    V_FRACT_F64,
    V_FREXP_EXP_I32_F32,
    V_FREXP_MANT_F32,
    V_CLREXCP,
    V_MOVRELD_B32,
    V_MOVRELS_B32,
    V_MOVRELSD_B32,
    V_CVT_F16_U16,
    V_CVT_F16_I16,
    V_CVT_U16_F16,
    V_CVT_I16_F16,
    V_RCP_F16,
    V_SQRT_F16,
    V_RSQ_F16,
    V_LOG_F16,
    V_EXP_F16,
    V_FREXP_MANT_F16,
    V_FREXP_EXP_I16_F16,
    V_FLOOR_F16,
    V_CEIL_F16,
    V_TRUNC_F16,
    V_RNDNE_F16,
    V_FRACT_F16,
    V_SIN_F16,
    V_COS_F16,
    V_EXP_LEGACY_F32,
    V_LOG_LEGACY_F32,

    V_CMP_CLASS_F32,
    V_CMPX_CLASS_F32,
    V_CMP_CLASS_F64,
    V_CMPX_CLASS_F64,
    V_CMP_CLASS_F16,
    V_CMPX_CLASS_F16,

    V_CMP_F16(OP16),
    V_CMPX_F16(OP16),
    V_CMP_F32(OP16),
    V_CMPX_F32(OP16),
    V_CMP_F64(OP16),
    V_CMPX_F64(OP16),
    V_CMP_I16(OP8),
    V_CMP_U16(OP8),
    V_CMPX_I16(OP8),
    V_CMPX_U16(OP8),
    V_CMP_I32(OP8),
    V_CMP_U32(OP8),
    V_CMPX_I32(OP8),
    V_CMPX_U32(OP8),
    V_CMP_I64(OP8),
    V_CMP_U64(OP8),
    V_CMPX_I64(OP8),
    V_CMPX_U64(OP8),

    V_MAD_LEGACY_F32,
    V_MAD_F32,
    V_MAD_I32_I24,
    V_MAD_U32_U24,
    V_CUBEID_F32,
    V_CUBESC_F32,
    V_CUBETC_F32,
    V_CUBEMA_F32,
    V_BFE_U32,
    V_BFE_I32,
    V_BFI_B32,
    V_FMA_F32,
    V_FMA_F64,
    V_LERP_U8,
    V_ALIGNBIT_B32,
    V_ALIGNBYTE_B32,
    V_MULLIT_F32,
    V_MIN3_F32,
    V_MIN3_I32,
    V_MIN3_U32,
    V_MAX3_F32,
    V_MAX3_I32,
    V_MAX3_U32,
    V_MED3_F32,
    V_MED3_I32,
    V_MED3_U32,
    V_SAD_U8,
    V_SAD_HI_U8,
    V_SAD_U16,
    V_SAD_U32,
    V_CVT_PK_U8_F32,
    V_DIV_FIXUP_F32,
    V_DIV_FIXUP_F64,
    V_LSHL_B64,
    V_LSHR_B64,
    V_ASHR_I64,
    V_ADD_F64,
    V_MUL_F64,
    V_MIN_F64,
    V_MAX_F64,
    V_LDEXP_F64,
    V_MUL_LO_U32,
    V_MUL_HI_U32,
    V_MUL_LO_I32,
    V_LDEXP_F32,
    V_READLANE_B32,
    V_WRITELANE_B32,
    V_BCNT_U32_B32,
    V_MBCNT_LO_U32_B32,
    V_MBCNT_HI_U32_B32,
    V_MUL_HI_I32,
    V_DIV_FMAS_F32,
    V_DIV_FMAS_F64,
    V_MSAD_U8,
    V_QSAD_PK_U16_U8,
    V_MQSAD_PK_U16_U8,
    V_MQSAD_U32_U8,
    V_MAD_U64_U32,
    V_MAD_I64_I32,
    V_MAD_F16,
    V_MAD_U16,
    V_MAD_I16,
    V_PERM_B32,
    V_FMA_F16,
    V_DIV_FIXUP_F16,
    V_CVT_PKACCUM_U8_F32,
    V_INTERP_P1_F32,
    V_INTERP_P2_F32,
    V_INTERP_MOV_F32,
    V_INTERP_P1LL_F16,
    V_INTERP_P1LV_F16,
    V_INTERP_P2_F16,

    V_MSAD_u32,
    V_QSAD_u32,
    V_MQSAD_u32,
    V_LSHLREV_B64,
    V_LSHRREV_B64,
    V_ASHRREV_I64,
    V_TRIG_PREOP_F64,
    V_BFM_B32,
    V_CVT_PKNORM_I16_F32,
    V_CVT_PKNORM_U16_F32,
    V_CVT_PKRTZ_F16_F32,
    V_CVT_PK_U16_U32,
    V_CVT_PK_I16_I32,
    V_OP1_OFFSET,

    V_DIV_SCALE_F32,
    V_DIV_SCALE_F64,

    S_LOAD_DWORD,
    S_LOAD_DWORDX2,
    S_LOAD_DWORDX4,
    S_LOAD_DWORDX8,
    S_LOAD_DWORDX16,
    S_BUFFER_LOAD_DWORD,
    S_BUFFER_LOAD_DWORDX2,
    S_BUFFER_LOAD_DWORDX4,
    S_BUFFER_LOAD_DWORDX8,
    S_BUFFER_LOAD_DWORDX16,
    S_STORE_DWORD,
    S_STORE_DWORDX2,
    S_STORE_DWORDX4,
    S_BUFFER_STORE_DWORD,
    S_BUFFER_STORE_DWORDX2,
    S_BUFFER_STORE_DWORDX4,
    S_DCACHE_INV,
    S_DCACHE_WB,
    S_DCACHE_INV_VOL,
    S_DCACHE_WB_VOL,
    S_MEMTIME,
    S_MEMREALTIME,
    S_ATC_PROBE,
    S_ATC_PROBE_BUFFER,

    FLAT_LOAD_UBYTE,
    FLAT_LOAD_SBYTE,
    FLAT_LOAD_USHORT,
    FLAT_LOAD_SSHORT,
    FLAT_LOAD_DWORD,
    FLAT_LOAD_DWORDX2,
    FLAT_LOAD_DWORDX4,
    FLAT_LOAD_DWORDX3,
    FLAT_STORE_BYTE,
    FLAT_STORE_SHORT,
    FLAT_STORE_DWORD,
    FLAT_STORE_DWORDX2,
    FLAT_STORE_DWORDX3,
    FLAT_STORE_DWORDX4,
    FLAT_ATOMIC_SWAP,
    FLAT_ATOMIC_CMPSWAP,
    FLAT_ATOMIC_ADD,
    FLAT_ATOMIC_SUB,
    FLAT_ATOMIC_SMIN,
    FLAT_ATOMIC_UMIN,
    FLAT_ATOMIC_SMAX,
    FLAT_ATOMIC_UMAX,
    FLAT_ATOMIC_AND,
    FLAT_ATOMIC_OR,
    FLAT_ATOMIC_XOR,
    FLAT_ATOMIC_INC,
    FLAT_ATOMIC_DEC,
    FLAT_ATOMIC_SWAP_X2,
    FLAT_ATOMIC_CMPSWAP_X2,
    FLAT_ATOMIC_ADD_X2,
    FLAT_ATOMIC_SUB_X2,
    FLAT_ATOMIC_SMIN_X2,
    FLAT_ATOMIC_UMIN_X2,
    FLAT_ATOMIC_SMAX_X2,
    FLAT_ATOMIC_UMAX_X2,
    FLAT_ATOMIC_AND_X2,
    FLAT_ATOMIC_OR_X2,
    FLAT_ATOMIC_XOR_X2,
    FLAT_ATOMIC_INC_X2,
    FLAT_ATOMIC_DEC_X2,

    BUFFER_LOAD_FORMAT_X,
    BUFFER_LOAD_FORMAT_XY,
    BUFFER_LOAD_FORMAT_XYZ,
    BUFFER_LOAD_FORMAT_XYZW,
    BUFFER_STORE_FORMAT_X,
    BUFFER_STORE_FORMAT_XY,
    BUFFER_STORE_FORMAT_XYZ,
    BUFFER_STORE_FORMAT_XYZW,
    BUFFER_LOAD_FORMAT_D16_X,
    BUFFER_LOAD_FORMAT_D16_XY,
    BUFFER_LOAD_FORMAT_D16_XYZ,
    BUFFER_LOAD_FORMAT_D16_XYZW,
    BUFFER_STORE_FORMAT_D16_X,
    BUFFER_STORE_FORMAT_D16_XY,
    BUFFER_STORE_FORMAT_D16_XYZ,
    BUFFER_STORE_FORMAT_D16_XYZW,
    BUFFER_LOAD_UBYTE,
    BUFFER_LOAD_SBYTE,
    BUFFER_LOAD_USHORT,
    BUFFER_LOAD_SSHORT,
    BUFFER_LOAD_DWORD,
    BUFFER_LOAD_DWORDX2,
    BUFFER_LOAD_DWORDX3,
    BUFFER_LOAD_DWORDX4,
    BUFFER_STORE_BYTE,
    BUFFER_STORE_SHORT,
    BUFFER_STORE_DWORD,
    BUFFER_STORE_DWORDX2,
    BUFFER_STORE_DWORDX3,
    BUFFER_STORE_DWORDX4,
    BUFFER_STORE_LDS_DWORD,
    BUFFER_WBINVL1,
    BUFFER_WBINVL1_VOL,
    BUFFER_ATOMIC_SWAP,
    BUFFER_ATOMIC_CMPSWAP,
    BUFFER_ATOMIC_ADD,
    BUFFER_ATOMIC_SUB,
    BUFFER_ATOMIC_SMIN,
    BUFFER_ATOMIC_UMIN,
    BUFFER_ATOMIC_SMAX,
    BUFFER_ATOMIC_UMAX,
    BUFFER_ATOMIC_AND,
    BUFFER_ATOMIC_OR,
    BUFFER_ATOMIC_XOR,
    BUFFER_ATOMIC_INC,
    BUFFER_ATOMIC_DEC,
    BUFFER_ATOMIC_SWAP_X2,
    BUFFER_ATOMIC_CMPSWAP_X2,
    BUFFER_ATOMIC_ADD_X2,
    BUFFER_ATOMIC_SUB_X2,
    BUFFER_ATOMIC_SMIN_X2,
    BUFFER_ATOMIC_UMIN_X2,
    BUFFER_ATOMIC_SMAX_X2,
    BUFFER_ATOMIC_UMAX_X2,
    BUFFER_ATOMIC_AND_X2,
    BUFFER_ATOMIC_OR_X2,
    BUFFER_ATOMIC_XOR_X2,
    BUFFER_ATOMIC_INC_X2,
    BUFFER_ATOMIC_DEC_X2,
}
#[derive(Debug, Clone, Copy)]
pub enum OP16 {
    F,
    LT,
    EQ,
    LE,
    GT,
    LG,
    GE,
    O,
    U,
    NGE,
    NLG,
    NGT,
    NLE,
    NEQ,
    NLT,
    TRU,
}
#[derive(Debug, Clone, Copy)]
pub enum OP8 {
    F,
    LT,
    EQ,
    LE,
    GT,
    LG,
    GE,
    TRU,
}

#[derive(Debug, Clone)]
pub struct VOP2 {
    pub src0: u16,
    pub vsrc1: u8,
    pub vdst: u8,
    pub op: I,
}

#[derive(Debug, Clone)]
pub struct VOP1 {
    pub src0: u16,
    pub op: I,
    pub vdst: u8,
}

#[derive(Debug, Clone)]
pub struct VOPC {
    pub src0: u16,
    pub vsrc1: u8,
    pub op: I,
}

#[derive(Debug, Clone)]
pub struct VOP3 {
    pub vdst: u8,
    pub abs: u8,
    pub opsel: u8,
    pub cm: u8,
    pub op: I,
    pub src0: u16,
    pub src1: u16,
    pub src2: u16,
    pub omod: u8,
    pub neg: u8,
}

#[derive(Debug, Clone)]
pub struct VOP3A {
    pub vdst: u8,
    pub abs: u8,
    pub clamp: u8,
    pub op: I,
    pub src0: u16,
    pub src1: u16,
    pub src2: u16,
    pub omod: u8,
    pub neg: u8,
}

#[derive(Debug, Clone)]
pub struct VOP3B {
    pub vdst: u8,
    pub sdst: u8,
    pub clamp: u8,
    pub op: I,
    pub src0: u16,
    pub src1: u16,
    pub src2: u16,
    pub omod: u8,
    pub neg: u8,
}

pub const VOPC_ENCODE: u32 = 0b0111110;
pub const VOP1_ENCODE: u32 = 0b0111111;
pub const VOP2_ENCODE: u32 = 0b0;
pub const VOP3_ENCODE: u32 = 0b110101;
pub const VOP3AB_ENCODE: u32 = 0b110100;

#[derive(Debug, Clone)]
pub struct SOP2 {
    pub ssrc0: u8,
    pub ssrc1: u8,
    pub sdst: u8,
    pub op: I,
}

#[derive(Debug, Clone)]
pub struct SOPK {
    pub simm16: u16,
    pub sdst: u8,
    pub op: I,
}

#[derive(Debug, Clone)]
pub struct SOP1 {
    pub ssrc0: u8,
    pub op: I,
    pub sdst: u8,
}

#[derive(Debug, Clone)]
pub struct SOPC {
    pub ssrc0: u8,
    pub ssrc1: u8,
    pub op: I,
}

#[derive(Debug, Clone)]
pub struct SOPP {
    pub simm16: u16,
    pub op: I,
}

pub const SOP2_ENCODE: u32 = 0b10;
pub const SOPK_ENCODE: u32 = 0b1011;
pub const SOP1_ENCODE: u32 = 0b101111101;
pub const SOPC_ENCODE: u32 = 0b101111110;
pub const SOPP_ENCODE: u32 = 0b101111111;

#[derive(Debug, Clone)]
pub struct SMRD {
    pub offset: u8,
    pub imm: u8,
    pub sbase: u8,
    pub sdst: u8,
    pub op: u8,
}

#[derive(Debug, Clone)]
pub struct SMEM {
    pub sbase: u8,
    pub sdata: u8,
    pub glc: u8,
    pub imm: u8,
    pub op: I,
    pub offset: u8,
}

pub const SMRD_ENCODE: u32 = 0b11000;
pub const SMEM_ENCODE: u32 = 0b110000;

#[derive(Debug, Clone)]
pub struct FLAT {
    pub glc: u8,
    pub slc: u8,
    pub op: I,
    pub addr: u8,
    pub data: u8,
    pub tfe: u8,
    pub vdst: u8,
}

pub const FLAT_ENCODE: u32 = 0b110111;

#[derive(Debug, Clone)]
pub struct MUBUF {
    pub offset: u16,
    pub offen: u8,
    pub idxen: u8,
    pub glc: u8,
    pub lds: u8,
    pub slc: u8,
    pub op: I,
    pub vaddr: u8,
    pub vdata: u8,
    pub srsrc: u8,
    pub tfe: u8,
    pub soffset: u8,
}

pub const MUBUF_ENCODE: u32 = 0b111000;

#[derive(Debug)]
pub enum InstFormat {
    SOP1(SOP1),
    SOP2(SOP2),
    SOPK(SOPK),
    SOPC(SOPC),
    SOPP(SOPP),
    SMRD(SMRD),
    SMEM(SMEM),
    VOP1(VOP1),
    VOP2(VOP2),
    VOP3(VOP3),
    VOPC(VOPC),
    VOP3A(VOP3A),
    VOP3B(VOP3B),
    FLAT(FLAT),
    MUBUF(MUBUF),
}
